services:
  bot:
    build: .
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/postgres'
      BASE_URL: ${BASE_URL}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
