services:
  bot:
    build: .
    depends_on:
      - postgres
    restart: always
    environment:
      DATABASE_URL: 'postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres'
      BASE_URL: ${BASE_URL}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
